dist: focal
sudo: false
language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-10
        packages:
            - nasm
            - clang-10
            - llvm-10-dev

script:
    - make
